# Generated by Django 4.1.1 on 2023-01-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_name',
            new_name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default=models.CharField(max_length=1000), max_length=1000),
        ),
    ]
