# Generated by Django 4.1.1 on 2023-01-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_rename_todo_name_todo_todo_todo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='task',
        ),
    ]
