# Generated by Django 4.1.1 on 2023-01-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_rename_todo_todo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
    ]
